### ISSUE TITLE
Alarm sensor

### ISSUE THREAD

**Issue by theo-69** [stanzhai/homebridge-mi-gateway-light#1]
Is it possible to include a alarm sensor that informs homekit that an alarm was triggered? Also can I hide the light and fm button?

**Comment by theo-69** [comment]
Really like your work @stanzhai , any infos?

**Comment by theo-69** [comment]
push

**Comment by stanzhai** [comment]
Thanks for your feedback, I haven't had much energy to improve this project lately.
You might want to focus on this project: https://www.npmjs.com/package/homebridge-mi-gateway-security

**Comment by theo-69** [comment]
thanks, same there no development anymore! Would like to help but I am a newbie with npm.
